title: Settings
data:
  site_name: 'കെ.എൽ.എസ്. എസ്.എ'
  personality: formal
  show_signup: false
  social:
    -
      id: EuhiJPTc
      name: Twitter
      url: 'https://twitter.com/statamic'
      icon: site/social-icons/twitter.svg
    -
      id: qkTUjQrH
      name: Github
      url: 'https://github.com/statamic/starter-kit-starters-creek'
      icon: site/social-icons/github.svg
    -
      id: j6I780kp
      name: Email
      url: 'mailto:jack@statamic.com'
      icon: site/social-icons/email.svg
